### ISSUE TITLE
Undo & Redo for Budgets

### ISSUE THREAD

**Issue by dingyuchen** [AY1920S1-CS2103T-W12-3/main#199]

**Comment by yewon0303** [comment]
Undo & redo works for budget. What is the bug you encountered?

**Comment by dingyuchen** [comment]
Undo on transaction does not revert change to budget

**Comment by yewon0303** [comment]
Fixed in #212 (commit: 5255586c06aac20c00c8ff2c3926902e7b5dffbd)
