### ISSUE TITLE
Show Ledger balance when in ledger tab

### ISSUE THREAD

**Issue by dingyuchen** [AY1920S1-CS2103T-W12-3/main#217]

**Comment by dingyuchen** [comment]
@joloong current tab in model?

**Comment by joloong** [comment]
Balance now doesn't change when filtering.  #244 

Does it fix your problem?

**Comment by dingyuchen** [comment]
ledger balance is not shown for undo and redo
Undo and redo needs to run handleSwitch code for proper behaviour.

mouse clicks also do not update balance for now
