### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by ZiHawkEye** [AY1920S1-CS2103T-W12-3/main#241]
1. No images present in undo example usage
https://github.com/AY1920S1-CS2103T-W12-3/main/blob/master/docs/UserGuide.adoc#3122-example-usage

2. Invalid split example in command summary
https://github.com/AY1920S1-CS2103T-W12-3/main/blob/master/docs/UserGuide.adoc#5-command-summary

3. Invalid set example
https://github.com/AY1920S1-CS2103T-W12-3/main/blob/master/docs/UserGuide.adoc#33-setting-a-budget--set

**Comment by joloong** [comment]
Fixed (2) in #244
