### ISSUE TITLE
Command bugs

### ISSUE THREAD

**Issue by ZiHawkEye** [AY1920S1-CS2103T-W12-3/main#242]
1. Share is set to 0 (No error thrown in application/error thrown in terminal)
split $/600 a/haidilao n/John Doe n/John Soe n/John Moe s/0 s/0 s/0

2. Identical names (No error thrown in application/error thrown in terminal)
split $/600 a/haidilao n/1 n/1 s/1 s/1

3. Amount field left blank (No error thrown in application/error thrown in terminal)
update t1 $/ d/22112019
split a/entry n/new person s/1 $/

4. Amount can be set to 0 if it is in double form 
split a/haidilao n/John Doe n/John Soe n/John Moe s/1 s/1 s/1 $/0.00

5. Allows for duplicate ledger entries if new person is created
split a/entry n/new person s/1 $/1
split a/entry n/new person s/1 $/1

6. Wrong error thrown? (Amounts should only be in integer or double, and it should not be blank)
split a/haidilao n/John Doe n/John Moe s/1 s/10000000000 $/1

7. Setting a transaction in the future will affect budgets with due dates before the transaction
out
set $/1 d/09112019
out n/out $/1 d/11112019

8. Setting a budget does not take into account existing transactions before the due date?
out n/out $/1 d/08112019
set $/1 d/09112019

**Comment by Berttwm** [comment]
Fixed 4 and 4
