### ISSUE TITLE
Clarification on set budget behaviour

### ISSUE THREAD

**Issue by dingyuchen** [AY1920S1-CS2103T-W12-3/main#249]
>Setting a budget does not take into account existing transactions before the due date?
out n/out $/1 d/08112019
set $/1 d/09112019

i think this is not a bug. Perhaps include in userguide?

**Comment by joloong** [comment]
@yewon0303  Fixed in https://github.com/AY1920S1-CS2103T-W12-3/main/pull/244/commits/c09b5f74ac0067976171c8181035f2e3bd55eb5b
